/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

    Point p1 = new Point();
    p1.x = 0;
    p1.y= 0;

    Point p2= new Point();
    p2.x = 1;
    p2.y= 1;

    System.out.println(distance(p1,p2));

    }

    public static double distance (Point p1, Point p2){
        return  Math.sqrt((p2.x - p1.x)*(p2.x - p1.x) + (p2.y - p1.y)*(p2.y - p1.y));
    }


}
